#配置端口
server:
  port: 8001
spring:
  application:
    name: demo-server
#配置为Eureka的服务端-服务注册中心
eureka:
  instance:
    hostname: localhost
  client:
    #Eureka客户端将要注册的注册中心的地址
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
#
logging:
  config: classpath:log/logback-config-prod.xml
#mysql
datasource:
  dbtest:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 10
    minIdle: 10
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    mapperLocation: classpath:db-test/*.xml
    scanDir: com.zhp.springcloud.dao