#配置端口
server:
  port: 8001
spring:
  application:
    name: demo-server
#配置为Eureka的服务端-服务注册中心
eureka:
  instance:
    hostname: localhost
  client:
    #Eureka客户端将要注册的注册中心的地址
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
