#配置端口
server:
  port: 8003
spring:
  application:
    name: api-getaway
#配置为Eureka的服务端-服务注册中心
eureka:
  client:
    #Eureka客户端将要注册的注册中心的地址
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
zuul:
  routes:
    demo-server: /api-demo/**
    demo-consumer: /api-consumer/**

